### ISSUE TITLE
Version 2.1.3 no longer compatible with python 2.7

### ISSUE THREAD

**Issue by AntoineD** [mdolab/pyXDSM#33]
## Type of issue
What types of issue is it?

- Breaking change (non-backwards-compatible fix or feature)

## Description
Installation under python 2.7 fails with version 2.1.3, installation is OK with 2.1.2.

### Current behavior
```
pip install pyxdsm
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pyxdsm
  Downloading https://files.pythonhosted.org/packages/a5/75/0e72f7ed01fda16cdc27ce5b676889eae7081bc383bf3a68622236cc52bc/pyXDSM-2.1.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /tmp/toto/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kzpqEX/pyxdsm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kzpqEX/pyxdsm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-kzpqEX/pyxdsm/pip-egg-info
         cwd: /tmp/pip-install-kzpqEX/pyxdsm/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kzpqEX/pyxdsm/setup.py", line 11, in <module>
        with open(path.join(this_directory, "README.md"), encoding="utf-8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by nwu63** [comment]
Hello Antoine, we do not support python 2 since its EOL was 2020/01/01. Of course you can fix this issue manually, but if you encounter any other issues you are on your own.
